<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <UseWpfUI>true</UseWpfUI>
        <LangVersion>12</LangVersion>
    </PropertyGroup>
    <ItemGroup>
      <Page Update="Views\Pages\ViewPlanSelectionPage.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
    </ItemGroup>
</Project>
