title:
  ru: ${{ gen.bundle_name }}
  en_us: ${{ gen.bundle_name }}

tooltip:
  ru: >- 
    Плагин делает это
    Для запуска: 
    
    1. Запустить плагин;
    
    2. Нажать ОК;
  en_us: >- 
    Plugin does this
    How to use:
    
    1. Start the plugin;
    
    2. Press OK;

assembly: ${{ gen.plugin_name }}.dll
command_class: ${{ gen.plugin_command }}

author: ${{ gen.author }}

min_revit_version: ${{ gen.min_revit_version }}
max_revit_version: ${{ gen.max_revit_version }}