<?xml version="1.0" encoding="UTF-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <ItemGroup Condition="$(RevitVersion) != ''">
        <Reference Include="Bim4Everyone.RevitFiltration">
            <HintPath>$(AppData)\pyRevit\Extensions\BIM4Everyone.lib\dosymep_libs\libs\$(RevitVersion)\Bim4Everyone.RevitFiltration.dll</HintPath>
            <Private>False</Private>
        </Reference>

        <Reference Include="Bim4Everyone.RevitFiltration.Controls">
            <HintPath>$(AppData)\pyRevit\Extensions\BIM4Everyone.lib\dosymep_libs\libs\$(RevitVersion)\Bim4Everyone.RevitFiltration.Controls.dll</HintPath>
            <Private>False</Private>
        </Reference>

        <Reference Include="Bim4Everyone.RevitFiltration.Ninject">
            <HintPath>$(AppData)\pyRevit\Extensions\BIM4Everyone.lib\dosymep_libs\libs\$(RevitVersion)\Bim4Everyone.RevitFiltration.Ninject.dll</HintPath>
            <Private>False</Private>
        </Reference>
    </ItemGroup>
</Project>
