<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <UseWpfUI>true</UseWpfUI>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>
    <ItemGroup>
      <Page Update="Views\Controls\ItemControl.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
    </ItemGroup>
</Project>
