name: build plugin

on:
  workflow_call:
    inputs:
      plugin-name:
        description: "Название плагина (профиль сборки Nuke)."
        required: true
        type: string
      use-devexpress:
        description: "Добавить источник пакетов DevExpress перед сборкой."
        required: false
        default: false
        type: boolean
      dotnet-version:
        description: "Версия .NET SDK."
        required: false
        default: '10.0.x'
        type: string
    secrets:
      EXTENSIONS_APP_TOKEN:
        required: true
      REVIT_PLUGINS_APP_TOKEN:
        required: true
      DEVEXPRESS_FEED_AUTHORIZATION_KEY:
        required: false

jobs:
  build:
    name: build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Install the .NET workload
      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      # Add DevExrepress package source: https://nuget.devexpress.com/
      - name: Add DevExpress package source
        if: ${{ inputs.use-devexpress }}
        run: dotnet nuget add source https://nuget.devexpress.com/api -n DXFeed -u DevExpress -p ${{ secrets.DEVEXPRESS_FEED_AUTHORIZATION_KEY }}

      - name: Run './build.cmd '
        run: ./build.cmd publish --profile ${{ inputs.plugin-name }} --pull-request-merged ${{ github.event.pull_request.merged }} --extensions-app-token ${{ secrets.EXTENSIONS_APP_TOKEN }} --revit-plugins-app-token ${{ secrets.REVIT_PLUGINS_APP_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
