name: publish RevitMirroredElements

on:
  workflow_dispatch:
  pull_request:
    types: [ closed, synchronize, review_requested ]
    branches: [ main, master ]
    paths:
      - '**RevitMirroredElements**.cs'
      - '**RevitMirroredElements**.xaml'
      - '**RevitMirroredElements**.csproj'

jobs:
  build:
    uses: ./.github/workflows/build-plugin.yml
    with:
      plugin-name: "RevitMirroredElements"
    secrets: inherit
