name: publish RevitShakeSpecs

on:
  workflow_dispatch:
  pull_request:
    types: [ closed, synchronize, review_requested ]
    branches: [ main, master ]
    paths:
      - '**RevitShakeSpecs**.cs'
      - '**RevitShakeSpecs**.xaml'
      - '**RevitShakeSpecs**.csproj'

jobs:
  build:
    uses: ./.github/workflows/build-plugin.yml
    with:
      plugin-name: "RevitShakeSpecs"
    secrets: inherit
