name: publish RevitDeleteUnused

on:
  workflow_dispatch:
  pull_request:
    types: [ closed, synchronize, review_requested ]
    branches: [ main, master ]
    paths:
      - '**RevitDeleteUnused**.cs'
      - '**RevitDeleteUnused**.xaml'
      - '**RevitDeleteUnused**.csproj'

jobs:
  build:
    uses: ./.github/workflows/build-plugin.yml
    with:
      plugin-name: "RevitDeleteUnused"
    secrets: inherit
