name: publish RevitFamilyExplorer

on:
  workflow_dispatch:
  pull_request:
    types: [ closed, synchronize, review_requested ]
    branches: [ main, master ]
    paths:
      - '**RevitFamilyExplorer**.cs'
      - '**RevitFamilyExplorer**.xaml'
      - '**RevitFamilyExplorer**.csproj'

jobs:
  build:
    uses: ./.github/workflows/build-plugin.yml
    with:
      plugin-name: "RevitFamilyExplorer"
    secrets: inherit
