name: publish RevitVolumeOfWork

on:
  workflow_dispatch:
  pull_request:
    types: [ closed, synchronize, review_requested ]
    branches: [ main, master ]
    paths:
      - '**RevitVolumeOfWork**.cs'
      - '**RevitVolumeOfWork**.xaml'
      - '**RevitVolumeOfWork**.csproj'

jobs:
  build:
    uses: ./.github/workflows/build-plugin.yml
    with:
      plugin-name: "RevitVolumeOfWork"
    secrets: inherit
