name: publish RevitOpeningSlopes

on:
  workflow_dispatch:
  pull_request:
    types: [ closed, synchronize, review_requested ]
    branches: [ main, master ]
    paths:
      - '**RevitOpeningSlopes**.cs'
      - '**RevitOpeningSlopes**.xaml'
      - '**RevitOpeningSlopes**.csproj'

jobs:
  build:
    uses: ./.github/workflows/build-plugin.yml
    with:
      plugin-name: "RevitOpeningSlopes"
    secrets: inherit
