name: publish RevitServerFolders

on:
  workflow_dispatch:
  pull_request:
    types: [ closed, synchronize, review_requested ]
    branches: [ main, master ]
    paths:
      - '**RevitServerFolders**.cs'
      - '**RevitServerFolders**.xaml'
      - '**RevitServerFolders**.csproj'

jobs:
  build:
    uses: ./.github/workflows/build-plugin.yml
    with:
      plugin-name: "RevitServerFolders"
    secrets: inherit
