name: publish RevitCreatingFiltersByValues

on:
  workflow_dispatch:
  pull_request:
    types: [ closed, synchronize, review_requested ]
    branches: [ main, master ]
    paths:
      - '**RevitCreatingFiltersByValues**.cs'
      - '**RevitCreatingFiltersByValues**.xaml'
      - '**RevitCreatingFiltersByValues**.csproj'

jobs:
  build:
    uses: ./.github/workflows/build-plugin.yml
    with:
      plugin-name: "RevitCreatingFiltersByValues"
    secrets: inherit
