name: publish RevitSleeves

on:
  workflow_dispatch:
  pull_request:
    types: [ closed, synchronize, review_requested ]
    branches: [ main, master ]
    paths:
      - '**RevitClashes**.cs'
      - '**RevitSleeves**.cs'
      - '**RevitSleeves**.xaml'
      - '**RevitSleeves**.csproj'

jobs:
  build:
    uses: ./.github/workflows/build-plugin.yml
    with:
      plugin-name: "RevitSleeves"
    secrets: inherit
