name: publish RevitLintelPlacement

on:
  workflow_dispatch:
  pull_request:
    types: [ closed, synchronize, review_requested ]
    branches: [ main, master ]
    paths:
      - '**RevitLintelPlacement**.cs'
      - '**RevitLintelPlacement**.xaml'
      - '**RevitLintelPlacement**.csproj'

jobs:
  build:
    uses: ./.github/workflows/build-plugin.yml
    with:
      plugin-name: "RevitLintelPlacement"
      use-devexpress: true
    secrets: inherit
