name: publish RevitListOfSchedules

on:
  workflow_dispatch:
  pull_request:
    types: [ closed, synchronize, review_requested ]
    branches: [ main, master ]
    paths:
      - '**RevitListOfSchedules**.cs'
      - '**RevitListOfSchedules**.xaml'
      - '**RevitListOfSchedules**.csproj'

jobs:
  build:
    uses: ./.github/workflows/build-plugin.yml
    with:
      plugin-name: "RevitListOfSchedules"
    secrets: inherit
