name: publish RevitExamplePlugin

on:
  workflow_dispatch:
  pull_request:
    types: [ closed, synchronize, review_requested ]
    branches: [ main, master ]
    paths:
      - '**RevitExamplePlugin**.cs'
      - '**RevitExamplePlugin**.xaml'
      - '**RevitExamplePlugin**.csproj'

jobs:
  build:
    uses: ./.github/workflows/build-plugin.yml
    with:
      plugin-name: "RevitExamplePlugin"
    secrets: inherit
