name: publish RevitSetLevelSection

on:
  workflow_dispatch:
  pull_request:
    types: [ closed, synchronize, review_requested ]
    branches: [ main, master ]
    paths:
      - '**RevitSetLevelSection**.cs'
      - '**RevitSetLevelSection**.xaml'
      - '**RevitSetLevelSection**.csproj'

jobs:
  build:
    uses: ./.github/workflows/build-plugin.yml
    with:
      plugin-name: "RevitSetLevelSection"
      use-devexpress: true
    secrets: inherit
