name: publish RevitRooms

on:
  workflow_dispatch:
  pull_request:
    types: [ closed, synchronize, review_requested ]
    branches: [ main, master ]
    paths:
      - '**RevitRooms**.cs'
      - '**RevitRooms**.xaml'
      - '**RevitRooms**.csproj'

jobs:
  build:
    uses: ./.github/workflows/build-plugin.yml
    with:
      plugin-name: "RevitRooms"
    secrets: inherit
