name: publish RevitCopyViews

on:
  workflow_dispatch:
  pull_request:
    types: [ closed, synchronize, review_requested ]
    branches: [ main, master ]
    paths:
      - '**RevitCopyViews**.cs'
      - '**RevitCopyViews**.xaml'
      - '**RevitCopyViews**.csproj'

jobs:
  build:
    uses: ./.github/workflows/build-plugin.yml
    with:
      plugin-name: "RevitCopyViews"
      use-devexpress: true
    secrets: inherit
