name: publish RevitSectionsConstructor

on:
  workflow_dispatch:
  pull_request:
    types: [ closed, synchronize, review_requested ]
    branches: [ main, master ]
    paths:
      - '**RevitSectionsConstructor**.cs'
      - '**RevitSectionsConstructor**.xaml'
      - '**RevitSectionsConstructor**.csproj'

jobs:
  build:
    uses: ./.github/workflows/build-plugin.yml
    with:
      plugin-name: "RevitSectionsConstructor"
    secrets: inherit
