name: publish RevitCopyInteriorSpecs

on:
  workflow_dispatch:
  pull_request:
    types: [ closed, synchronize, review_requested ]
    branches: [ main, master ]
    paths:
      - '**RevitCopyInteriorSpecs**.cs'
      - '**RevitCopyInteriorSpecs**.xaml'
      - '**RevitCopyInteriorSpecs**.csproj'

jobs:
  build:
    uses: ./.github/workflows/build-plugin.yml
    with:
      plugin-name: "RevitCopyInteriorSpecs"
    secrets: inherit
