name: publish RevitAreaBoundaries

on:
  workflow_dispatch:
  pull_request:
    types: [ closed, synchronize, review_requested ]
    branches: [ main, master ]
    paths:
      - '**RevitAreaBoundaries**.cs'
      - '**RevitAreaBoundaries**.xaml'
      - '**RevitAreaBoundaries**.csproj'

jobs:
  build:
    uses: ./.github/workflows/build-plugin.yml
    with:
      plugin-name: "RevitAreaBoundaries"
    secrets: inherit
