name: publish RevitFinishing

on:
  workflow_dispatch:
  pull_request:
    types: [ closed, synchronize, review_requested ]
    branches: [ main, master ]
    paths:
      - '**RevitFinishing**.cs'
      - '**RevitFinishing**.xaml'
      - '**RevitFinishing**.csproj'

jobs:
  build:
    uses: ./.github/workflows/build-plugin.yml
    with:
      plugin-name: "RevitFinishing"
    secrets: inherit
