name: RevitMepTotals publish

on:
  push:
    branches:
      - 'vlastroG/workflow'
    paths:
      - '**RevitMepTotals**.cs'
      - '**RevitMepTotals**.xaml'

env:
  Plugin_Repo_Url: https://github.com/Bim4Everyone/BIMExtensions.git # Plugin's github repository for pyRevit ribbon
  Plugin_Name: RevitMepTotals                                        # Plugin name

jobs:
  build:
    name: build
    runs-on: windows-latest

    steps:
    - name: Checkout RevitPlugins
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .net8 workload
    - name: Install .net8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x.x

    # Install nuke-build
    - name: Install nuke-build
      run: dotnet tool install Nuke.GlobalTool --global
