name: RevitRoomTagPlacement

on:
  push:
    paths:
      - 'RevitRoomTagPlacement/**'
      - '**.cs'

env:
  output: C:\Users\Tikhomirov_am\Documents\Projects - Tikhomirov A. M\RevitPlugins\bin
  plugin_name: RevitRoomTagPlacement

jobs:
  windows-latest:
    name: windows-latest
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache .nuke/temp, ~/.nuget/packages
        uses: actions/cache@v2
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}
      - name: Run './build.cmd '
        run: ./build.cmd publish --plugin-name $plugin_name --output $output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
