name: RevitMepTotals publish

on:
  push:
    branches:
      - 'vlastroG:vlastroG/workflow'
    paths:
      - '**RevitMepTotals**.cs'
      - '**RevitMepTotals**.xaml'

env:
  Plugin_Repo_Url: https://github.com/vlastroG/BIMExtensions.git
  Plugin_Name: RevitMepTotals
  Bim4Everyone_lib_Repo_Url: https://github.com/Bim4Everyone/BIM4Everyone.git

jobs:
  build:
    name: build
    runs-on: windows-latest

    steps:

    # Install the .net8 workload
    - name: Install .net8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x.x

    # Install nuke-build
    - name: Install nuke-build
      run: dotnet tool install Nuke.GlobalTool --global

    - name: Add DevExpress package source
      run: dotnet nuget add source https://nuget.devexpress.com/api -n DXFeed -u DevExpress -p ${{ secrets.DEVEXPRESS_FEED_AUTHORIZATION_KEY }}

    - name: Clone Bim4Everyone.lib
      run: git clone Bim4Everyone_lib_Repo_Url $env:APPDATA\pyRevit\Extensions\BIM4Everyone.lib

    # https://gist.github.com/MarkTiedemann/c0adc1701f3f5c215fc2c2d5b1d5efd3
    - name: Download pyRevit latest release
      run: |
        $repo = "eirannejad/pyRevit"
        $releases = "https://api.github.com/repos/$repo/releases"
        echo $releases
        $tag = (curl.exe -L $releases | ConvertFrom-Json)[0].tag_name.Split("v")[1]
        echo $tag
        $file = "pyRevit_" + $tag + "_signed.exe"
        echo $file
        $download = "https://github.com/$repo/releases/latest/download/$file"
        echo $download
        curl.exe -LO $download

    - name: Install pyRevit
      run: |
        echo $file
        start $file /silent

    - name: Remove pyRevit installer
      run: |
        echo $file
        rm $file

    - name: Checkout RevitPlugins
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
