name: publish ${{ gen.plugin_name }}

on:
  workflow_dispatch:
  pull_request:
    types: [ closed, synchronize, review_requested ]
    branches: [ main, master ]
    paths:
      - '**${{ gen.plugin_name }}**.cs'
      - '**${{ gen.plugin_name }}**.xaml'
      - '**${{ gen.plugin_name }}**.csproj'

jobs:
  build:
    uses: ./.github/workflows/build-plugin.yml
    with:
      plugin-name: "${{ gen.plugin_name }}"
      use-devexpress: ${{ gen.use_devexpress }}
    secrets: inherit
